### PR TITLE
Pull Request to support FLOAT from Emerald City

### PR DESCRIPTION
**Pull request by Bamthelearner**

### CODE REVIEW

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
Could you resolve merge conflicts? Our bi-weekly release is this Thursday, would be great to get your changes in before that

**Comment by Bamthelearner** [comment]
@niveda-krish 
I just solved the conflict and would like you to review again before pulling to the main branch.
Thank you very much for your prompt reply!

**Comment by niveda-krish** [comment]
Sorry to ask again, could you resolve merge conflicts one more time? Another PR got merged

**Comment by Bamthelearner** [comment]
> The conflicts are solved!
Thanks for the reminder

**Pull request merged**
