### PR TITLE
Use a stringStartsWith function to check if niftory urls are correct

### PR DESCRIPTION
**Pull request by arturenault**

### CODE REVIEW

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
Got a merge conflict, could you please resolve? Looks good otherwise! Thank you :)

**Comment by niveda-krish** [comment]
@arturenault friendly reminder to resolve merge conflicts so that we can get these changes in before our release this week

**Comment by arturenault** [comment]
Done

**Comment by arturenault** [comment]
Friendly ping on approval

**Pull request merged**
