### PR TITLE
Update niftory contracts to fix IPFS and external domain urls

### PR DESCRIPTION
**Pull request by arturenault**

### CODE REVIEW

**Comment by niveda-krish** [comment]
Looks good - could you update testnet as well?

**Comment by arturenault** [comment]
Sorry for the delay - updated testnet as well.

**Comment by arturenault** [comment]
Friendly ping on approval for this or :)

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
Sorry for the delay on this, approved and merged

**Pull request merged**
