### PR TITLE
Add SCMP NFT

### PR DESCRIPTION
**Pull request by Peixer**

### CODE REVIEW

**Comment by niveda-krish** [comment]
Hey @Peixer thanks for submitting this PR, can we add tests for mainnet too?

**Comment by Peixer** [comment]
@niveda-krish I added the mainnet tests :)

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
Ah sorry, could you resolve the merge conflicts here as well? Thank you!

**Comment by Peixer** [comment]
@niveda-krish yes, just give a minute

**Comment by Peixer** [comment]
@niveda-krish done!

**Pull request merged**
