### PR TITLE
Add metadata support to Ozone Metaverse 

### PR DESCRIPTION
**Pull request by koftunka**
Adding `metadata` support for the smart contract

Screen Shot 2022-05-05 at 12 15 33 AM

Screen Shot 2022-05-05 at 12 43 59 AM

### CODE REVIEW

**Comment by koftunka** [comment]
@niveda-krish @albeethekid @rambhask please let me know if there is anything pending on this PR. Thank you!

**Comment by ozoneuniverse** [comment]
@koftunka : please bear with @albeethekid  & team, I am sure they are slammed. 
Thanks @niveda-krish & team !

**Comment by ozoneuniverse** [comment]
hello @albeethekid  and @niveda-krish - any update here?

**Comment by ozoneuniverse** [comment]
let us know if all looking good please

**Comment by niveda-krish** [comment]
Hey @ozoneuniverse taking a look now

**Review by niveda-krish — APPROVED** [review]

**Pull request merged**
