### PR TITLE
Change Metadata type to {String:String?}

### PR DESCRIPTION
**Pull request by niveda-krish**
Some contracts need to be updated to include metadata in the new format. Tagging the owners here:
1. NowggNFT @sudhanshu-bst

### CODE REVIEW

**Comment by sudhanshu-bst** [comment]
@niveda-krish  can you share the new format details to which I need to update my metadata

**Comment by niveda-krish** [comment]
Hey @sudhanshu-bst , its  pub let metadata: {String: String?}

**Comment by sudhanshu-bst** [comment]
Okay, will add a fix for it @niveda-krish. Also any updates when this will get reflected in your API shared with blocto?

**Comment by niveda-krish** [comment]
Hey Sudhanshu, I just merged the changes - since the types were not string for NowggNFT before, this was already broken in our NFT API. I can take a look and merge your PR whenever you are ready!

**Pull request merged**
