### PR TITLE
feat(collection): Add Barter Yard Collection listing

### PR DESCRIPTION
**Pull request by AlexandreBarbier**

### CODE REVIEW

**Comment by AlexandreBarbier** [comment]
Sorry for the linter >_<

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
Thanks for adding support for Barter Yard - I approved the changes, could you resolve merge conflicts?

**Comment by AlexandreBarbier** [comment]
Hello, during the resolution of the merge conflict I realise that someone change in testnet/getNFTs.cdc the struct name of NFTContract to NFTContractData but this change is not in mainnet/getNFTs.cdc. Maybe it's normal but it can lead to confusion. Disregard this command if this is normal.

**Comment by niveda-krish** [comment]
Yeah noticed that, they added this in testnet because their contract name is NFTContract lol. They might add it to mainnet later is my guess

**Pull request merged**
