### PR TITLE
Add Bitku

### PR DESCRIPTION
**Pull request by docmarionum1**
This adds support for [Bitku](https://bitku.art/).

This NFT doesn't have any external media, just text stored on the blockchain.

I wasn't 100% sure how the `description` field is used by consumers of Alchemy, so I included the text of the NFT in both the `description` and the metadata. But I'm not sure if that's necessary.

### CODE REVIEW

**Review by niveda-krish — APPROVED** [review]

**Comment by niveda-krish** [comment]
This PR has merge conflicts, could you pull from main and resolve the conflicts? I can merge the PR after

**Comment by niveda-krish** [comment]
Hey @docmarionum1 , just waiting on your merge conflict update and I can check this in! Thanks for submitting your change :D

**Comment by niveda-krish** [comment]
Thank you! external_domain_view_url is a url where anyone can view the NFT on the official site. token_uri is similar to the Eth concept - points to a url where we can fetch metadata + media information (eg ipfs/arweave)

**Comment by niveda-krish** [comment]
where is the media url stored in the case of Bitku?

**Comment by docmarionum1** [comment]
> where is the media url stored in the case of Bitku?

There is no external media, it's all stored on chain under the `.text` attribute.

**Pull request merged**
